name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.x

    - name: Setup Go Environment
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install dependencies
      run: make restore

    - name: Build & Package
      run: make package

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Create Release
      shell: bash
      run: |
        go env
        go get -u github.com/tcnksm/ghr
        ghr -t ${{ secrets.GITHUB_TOKEN }} -b 'WebTty release. Look at the changelog for more info' ${{ steps.get_version.outputs.VERSION }} ./artifacts/

    - name: Push to nuget
      run: dotnet nuget push artifacts/**/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
